### PR TITLE
Add Appveyor yml file to run tests against Windows PowerShell 5.1, PowerShell Core on Windows and PowerShell Core on Linux (Ubuntu)

### PR DESCRIPTION
**Pull request by bergmeister**
Run build/test script and upload test results in AppVeyor. Just add this repo to AppVeyor and it will work out of the box. [Here](https://ci.appveyor.com/project/bergmeister/assert/builds/20992959) is a build from my fork.

The build that uses Windows PowerShell [here](https://ci.appveyor.com/project/bergmeister/assert/builds/20992959/job/tj1mmpphre2veh4u) exhibits a bug in `Assert` btw:
image

### CODE REVIEW

**Comment by nohwnd** [comment]
Thanks, I am already building against some Linux on Travis. Is there any benefit in having two builds that target Linux?

The message is not a bug, it's a warning that if seen by an end-user should be reported because then it means that Options are not passed correctly in recursive calls, but in the build it is normal because I am not providing the options in many tests. A solution to that would be making the Option parameter mandatory and give options to all tests, but I did not want to do that (yet?).

**Comment by nohwnd** [comment]
One more question, is it possible to run against PowerShell 3 & 4 on AppVeyor as well?

**Comment by bergmeister** [comment]
Well, before the build definition was not part of source control and was only testing against ps5.1
Now we  also test against v6 on Linux and Windows.
Appveyor has a legacy WMF4 that one can request, I could help you with that.

**Comment by IlyaFinkelshteyn** [comment]
@bergmeister Enabled `WMF4`. We do not have `WMF3` though.

**Comment by bergmeister** [comment]
@IlyaFinkelshteyn I tired using the `WMF4` image in [this ](https://github.com/nohwnd/Assert/pull/44) new PR but it does not seem to work

**Comment by nohwnd** [comment]
@IlyaFinkelshteyn thanks!

**Comment by bergmeister** [comment]
@IlyaFinkelshteyn Thanks, sorry, I forgot about the space in the name. Yes, it works now, it is just the code now that needs adaption to work with that PowerShell version :)

**Comment by IlyaFinkelshteyn** [comment]
@bergmeister great, thank for the update!

**Pull request merged**
