### PR TITLE
Auto-fix PSSA warnings

### PR DESCRIPTION
**Pull request by bergmeister**
Auto-fix PSSA warnings:
- Use proper cmdet name instead of alias for better readability and slightly faster runtime performance due to faster command lookup
- Remove trailing whitespace, resulting in a smaller payload of the whole module and git repo

I did this as follows to preserve existing Ascii encoding:
````powershell
Invoke-ScriptAnalyzer . -Recurse -Fix;  gci -File -Filter *.ps1  -Recurse | % { $c = cat $_.FullName -Raw; Set-Content -Path $_.fullname -Encoding Ascii -Value $c -NoNewline; }
````

### CODE REVIEW

**Comment by bergmeister** [comment]
needs more work

**Comment by nohwnd** [comment]
I couldn't find any files in the project that are ASCII, the sizable amount I checked were all in UTF8 without BOM. Are you sure ascii is correct? I tested it now with utf8 and the module seems to work just fine after the fixes. 

```powershell
powershell -NoProfile -Command Invoke-ScriptAnalyzer . -Recurse -Fix
```

Btw how long it takes to finish on your computer? Here it takes a minute or maybe even two. Is it normally that slow?

**Comment by bergmeister** [comment]
In the diff presented by Tortoise Git, it seemed to be that previosly it was Ascii, hence why I changed it back to Ascii. However, by looking at the Encoding of `master` in `Notepad++` it seems to be `UTF8-BOM`. When I wrote the `-Fix` switch I tried to preserve encoding as good as possible when reading and writing to the file so maybe `TortoiseGit` is just wrong when it shows me the diff, I'll revert the encoding change.

**Comment by nohwnd** [comment]
When I look at any file I see just UTF8 without BOM. If there are files with BOM then they should become UTF8 without BOM anyway.

On 14 Dec 2018, at 19:34, Christoph Bergmeister [MVP] <notifications@github.com<mailto:notifications@github.com>> wrote:


In the diff presented by Tortoise Git, it seemed to be that previosly it was Ascii, hence why I changed it back to Ascii. However, by looking at the Encoding of master in Notepad++ it seems to be UTF8-BOM. When I wrote the -Fix switch I tried to preserve encoding as good as possible when reading and writing to the file so maybe TortoiseGit is just wrong when it shows me the diff, I'll revert the encoding change.

**Comment by bergmeister** [comment]
Ok, I'll close this in favour of PR #43 where I don't change the encoding. Changing the encoding is a bit tricky, so I'll leave that up to you then (I tried different techniques but different editors were showing me different values)

**Pull request closed without merging**
